#server:
#  port: 8081
#
#spring:
#  application:
#    name: api-paassenger
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: 1aa6f35c-21bc-4dfb-bae2-93ebe539fc17
## dataid:api-passenger-sentinel-flow-rule group:sentinel-goup
#    sentinel:
#      transport:
#        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
#        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
#      web-context-unify: false
#      datasource:
#        api-passenger-sentinel-flow-rule:
#          nacos:
#            server-addr: localhost:8848
#            namespace: 1aa6f35c-21bc-4dfb-bae2-93ebe539fc17
#            data-id: api-passenger-sentinel-flow-rule
#            group-id: sentinel-goup
#            data-type: json  #数据格式
#            rule-type: flow #流控规则
#
#
#
#  redis:
#    database: 0
#    port: 6379
##    password: #111111
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    host: localhost                            #192.168.6.112
#logging:
#  level:
#    org.example: debug
#
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 1000
#        read-timeout: 500
#  sentinel:
#    enabled: true
#
#
#seata:
#  service:
#    vgroup-mapping:
#      taxi: seata-tc
#    grouplist:
#      seata-tc: localhost:8091
#  tx-service-group: taxi